#!/usr/bin/env python

import argparse
import subprocess

def main():
  ap = argparse.ArgumentParser()
  ap.add_argument('-f', '--fields', default='.Level,.Timestamp,.Hostname,.Pid,.Source,.Message',
                  help='comma delimited list of jq field selectors')
  ap.add_argument('awk_prog')

  args = ap.parse_args()

  jq_proc = subprocess.Popen(['jq', '-r', '[%s]|@tsv' % args.fields], stdout=subprocess.PIPE)
  subprocess.check_call(['awk', '-F\t', args.awk_prog], stdin=jq_proc.stdout)




if __name__ == '__main__':
  main()
